# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: master
            
    - name: install nodejs
      uses: actions/setup-node@v1
      
    - name: configue gitbook
      run: |
        npm install -g gitbook-cli          
        gitbook install
        npm install -g gitbook-summary
                
    - name: generate _book folder
      run: |
        book sm
        gitbook build
        cp SUMMARY.md _book
               
    #- name: GitHub Pages
    #  # You may pin to the exact commit or the version.
    #  # uses: crazy-max/ghaction-github-pages@1510b11c0c2f843eafb8ff41b3da8c467c8d4a9f
    #  uses: crazy-max/ghaction-github-pages@v2.2.0
    #  with:
    #    # GitHub repository where assets will be deployed (default current)
    #    repo: # optional
    #    # Git branch where assets will be deployed
    #    target_branch: # optional, default is gh-pages
    #    # Create incremental commit instead of doing push force
    #    keep_history: # optional, default is false
    #    # Allow an empty commit to be created
    #    allow_empty_commit: # optional, default is true
    #    # Build directory to deploy
    #    build_dir: _book
    #    # The committer name and email address
    #    committer: # optional
    #    # The author name and email address
    #    author: # optional
    #    # Commit message
    #    commit_message: # optional
    #    # Write the given domain name to the CNAME file
    #    fqdn: # optional
    #    # Allow Jekyll to build your site
    #    jekyll: # optional, default is true
        
    - name: push _book to branch gh-pages 
      env:
        TOKEN: ${{ secrets.TOKEN }}
        REF: github.com/${{github.repository}}
        MYEMAIL: snowfly1993@gmail.com                  # ！！记得修改为自己github设置的邮箱
        MYNAME: ${{github.repository_owner}}          
      run: |
        echo "$TOKEN"
        echo "$REF"
        echo "$MYEMAIL"
        echo "$MYNAME"
        cd _book
        git config --global user.email "${MYEMAIL}"
        git config --global user.name "${MYNAME}"
        git init
        git remote add origin https://${REF}
        git add . 
        git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
        git branch -M master
        git push --force --quiet "https://${TOKEN}@${REF}" master:gh-pages

